# Generated by Django 5.2 on 2025-04-16 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseekers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='name',
            field=models.CharField(default='Unnamed', max_length=100),
        ),
    ]
