# Generated by Django 5.2 on 2025-04-16 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobpostings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='description',
            field=models.TextField(default='No description provided'),
        ),
    ]
